//
//  GroupMeBooks.swift
//  GroupMeBooks
//
//  Created by James O'Brien on 09/12/2015.
//  Copyright (c) 2015 (null). All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//



import UIKit

public class GroupMeBooks : NSObject {

    //// Cache

    private struct Cache {
        static let white50: UIColor = UIColor(red: 1.000, green: 1.000, blue: 1.000, alpha: 0.500)
        static let black20: UIColor = UIColor(red: 0.000, green: 0.000, blue: 0.000, alpha: 0.200)
        static let shadowColor: UIColor = UIColor(red: 0.000, green: 0.000, blue: 0.000, alpha: 1.000)
        static let white60: UIColor = UIColor(red: 1.000, green: 1.000, blue: 1.000, alpha: 0.600)
        static let white40: UIColor = UIColor(red: 1.000, green: 1.000, blue: 1.000, alpha: 0.400)
        static let slateStartColor: UIColor = UIColor(red: 1.000, green: 1.000, blue: 1.000, alpha: 1.000)
        static let slateEndColor: UIColor = UIColor(red: 1.000, green: 1.000, blue: 1.000, alpha: 0.860)
        static let messageListEndColor: UIColor = UIColor(red: 0.953, green: 0.953, blue: 0.953, alpha: 1.000)
        static let white90: UIColor = UIColor(red: 1.000, green: 1.000, blue: 1.000, alpha: 0.900)
        static let white80: UIColor = UIColor(red: 1.000, green: 1.000, blue: 1.000, alpha: 0.800)
        static let darkPurple: UIColor = UIColor(red: 0.200, green: 0.090, blue: 0.286, alpha: 1.000)
        static let purple: UIColor = UIColor(red: 0.386, green: 0.178, blue: 0.549, alpha: 1.000)
        static let white10: UIColor = UIColor(red: 1.000, green: 1.000, blue: 1.000, alpha: 0.150)
        static let black10: UIColor = UIColor(red: 0.000, green: 0.000, blue: 0.000, alpha: 0.100)
        static let translucentCardGradient: CGGradient = CGGradientCreateWithColors(CGColorSpaceCreateDeviceRGB(), [GroupMeBooks.white60.CGColor, GroupMeBooks.white40.CGColor], [0, 1])!
        static let slateGradient: CGGradient = CGGradientCreateWithColors(CGColorSpaceCreateDeviceRGB(), [GroupMeBooks.slateStartColor.CGColor, GroupMeBooks.slateEndColor.CGColor], [0, 1])!
        static let messageListGradient: CGGradient = CGGradientCreateWithColors(CGColorSpaceCreateDeviceRGB(), [UIColor.whiteColor().CGColor, GroupMeBooks.messageListEndColor.CGColor], [0, 1])!
        static let lessTranslucent: CGGradient = CGGradientCreateWithColors(CGColorSpaceCreateDeviceRGB(), [GroupMeBooks.white90.CGColor, GroupMeBooks.white80.CGColor], [0, 1])!
        static let purpleGradient: CGGradient = CGGradientCreateWithColors(CGColorSpaceCreateDeviceRGB(), [GroupMeBooks.purple.CGColor, GroupMeBooks.darkPurple.CGColor], [0, 1])!
        static let logoShadow: NSShadow = NSShadow(color: UIColor.blackColor().colorWithAlphaComponent(0.2), offset: CGSizeMake(0.1, 2.1), blurRadius: 4)
        static var imageOfLogoPurpleOnWhite: UIImage?
        static var logoPurpleOnWhiteTargets: [AnyObject]?
        static var imageOfFace: UIImage?
        static var faceTargets: [AnyObject]?
        static var imageOfLogoPurpleOnWhiteSmall: UIImage?
        static var logoPurpleOnWhiteSmallTargets: [AnyObject]?
        static var imageOfSingleBubble: UIImage?
        static var singleBubbleTargets: [AnyObject]?
        static var imageOfDualBubble: UIImage?
        static var dualBubbleTargets: [AnyObject]?
    }

    //// Colors

    public class var white50: UIColor { return Cache.white50 }
    public class var black20: UIColor { return Cache.black20 }
    public class var shadowColor: UIColor { return Cache.shadowColor }
    public class var white60: UIColor { return Cache.white60 }
    public class var white40: UIColor { return Cache.white40 }
    public class var slateStartColor: UIColor { return Cache.slateStartColor }
    public class var slateEndColor: UIColor { return Cache.slateEndColor }
    public class var messageListEndColor: UIColor { return Cache.messageListEndColor }
    public class var white90: UIColor { return Cache.white90 }
    public class var white80: UIColor { return Cache.white80 }
    public class var darkPurple: UIColor { return Cache.darkPurple }
    public class var purple: UIColor { return Cache.purple }
    public class var white10: UIColor { return Cache.white10 }
    public class var black10: UIColor { return Cache.black10 }

    //// Gradients

    public class var translucentCardGradient: CGGradient { return Cache.translucentCardGradient }
    public class var slateGradient: CGGradient { return Cache.slateGradient }
    public class var messageListGradient: CGGradient { return Cache.messageListGradient }
    public class var lessTranslucent: CGGradient { return Cache.lessTranslucent }
    public class var purpleGradient: CGGradient { return Cache.purpleGradient }

    //// Shadows

    public class var logoShadow: NSShadow { return Cache.logoShadow }

    //// Drawing Methods

    public class func drawLogoWhiteOnPurple() {
        //// General Declarations
        let context = UIGraphicsGetCurrentContext()

        //// Group
        //// Halo Drawing
        let haloPath = UIBezierPath()
        haloPath.moveToPoint(CGPointMake(179.78, 24.76))
        haloPath.addCurveToPoint(CGPointMake(169.89, 14.88), controlPoint1: CGPointMake(179.78, 19.3), controlPoint2: CGPointMake(175.35, 14.88))
        haloPath.addCurveToPoint(CGPointMake(162.73, 17.96), controlPoint1: CGPointMake(167.07, 14.88), controlPoint2: CGPointMake(164.53, 16.06))
        haloPath.addCurveToPoint(CGPointMake(148, 13.34), controlPoint1: CGPointMake(158.55, 15.05), controlPoint2: CGPointMake(153.48, 13.34))
        haloPath.addCurveToPoint(CGPointMake(133.16, 18.05), controlPoint1: CGPointMake(142.47, 13.34), controlPoint2: CGPointMake(137.35, 15.1))
        haloPath.addCurveToPoint(CGPointMake(125.96, 15.23), controlPoint1: CGPointMake(131.26, 16.3), controlPoint2: CGPointMake(128.74, 15.23))
        haloPath.addCurveToPoint(CGPointMake(120.34, 16.85), controlPoint1: CGPointMake(123.89, 15.23), controlPoint2: CGPointMake(121.97, 15.83))
        haloPath.addCurveToPoint(CGPointMake(100.64, 5.31), controlPoint1: CGPointMake(116.47, 9.96), controlPoint2: CGPointMake(109.1, 5.31))
        haloPath.addCurveToPoint(CGPointMake(82.02, 15.1), controlPoint1: CGPointMake(92.91, 5.31), controlPoint2: CGPointMake(86.1, 9.19))
        haloPath.addCurveToPoint(CGPointMake(68.57, 9.41), controlPoint1: CGPointMake(78.61, 11.59), controlPoint2: CGPointMake(73.85, 9.41))
        haloPath.addCurveToPoint(CGPointMake(59.04, 12.03), controlPoint1: CGPointMake(65.09, 9.41), controlPoint2: CGPointMake(61.83, 10.38))
        haloPath.addCurveToPoint(CGPointMake(46.89, 0), controlPoint1: CGPointMake(58.97, 5.38), controlPoint2: CGPointMake(53.56, 0))
        haloPath.addCurveToPoint(CGPointMake(34.74, 12.15), controlPoint1: CGPointMake(40.18, 0), controlPoint2: CGPointMake(34.74, 5.44))
        haloPath.addCurveToPoint(CGPointMake(34.77, 12.61), controlPoint1: CGPointMake(34.74, 12.3), controlPoint2: CGPointMake(34.76, 12.45))
        haloPath.addCurveToPoint(CGPointMake(30.77, 12.31), controlPoint1: CGPointMake(33.47, 12.42), controlPoint2: CGPointMake(32.13, 12.31))
        haloPath.addCurveToPoint(CGPointMake(19.71, 14.74), controlPoint1: CGPointMake(26.82, 12.31), controlPoint2: CGPointMake(23.08, 13.19))
        haloPath.addCurveToPoint(CGPointMake(13.38, 13.15), controlPoint1: CGPointMake(17.83, 13.72), controlPoint2: CGPointMake(15.68, 13.15))
        haloPath.addCurveToPoint(CGPointMake(0, 26.53), controlPoint1: CGPointMake(6, 13.15), controlPoint2: CGPointMake(0, 19.14))
        haloPath.addCurveToPoint(CGPointMake(4.38, 36.4), controlPoint1: CGPointMake(0, 30.44), controlPoint2: CGPointMake(1.69, 33.95))
        haloPath.addCurveToPoint(CGPointMake(4.26, 38.83), controlPoint1: CGPointMake(4.3, 37.2), controlPoint2: CGPointMake(4.26, 38.01))
        haloPath.addCurveToPoint(CGPointMake(30.77, 65.35), controlPoint1: CGPointMake(4.26, 53.47), controlPoint2: CGPointMake(16.13, 65.35))
        haloPath.addCurveToPoint(CGPointMake(46.06, 60.5), controlPoint1: CGPointMake(36.47, 65.35), controlPoint2: CGPointMake(41.74, 63.55))
        haloPath.addCurveToPoint(CGPointMake(63.32, 69.29), controlPoint1: CGPointMake(49.95, 65.82), controlPoint2: CGPointMake(56.22, 69.29))
        haloPath.addCurveToPoint(CGPointMake(63.83, 69.27), controlPoint1: CGPointMake(63.49, 69.29), controlPoint2: CGPointMake(63.66, 69.27))
        haloPath.addCurveToPoint(CGPointMake(77.86, 79.22), controlPoint1: CGPointMake(65.87, 75.06), controlPoint2: CGPointMake(71.37, 79.22))
        haloPath.addCurveToPoint(CGPointMake(91.97, 69.04), controlPoint1: CGPointMake(84.43, 79.22), controlPoint2: CGPointMake(90, 74.95))
        haloPath.addCurveToPoint(CGPointMake(103.86, 76.23), controlPoint1: CGPointMake(94.22, 73.31), controlPoint2: CGPointMake(98.7, 76.23))
        haloPath.addCurveToPoint(CGPointMake(116.99, 65.6), controlPoint1: CGPointMake(110.31, 76.23), controlPoint2: CGPointMake(115.7, 71.67))
        haloPath.addCurveToPoint(CGPointMake(119.84, 65.82), controlPoint1: CGPointMake(117.93, 65.73), controlPoint2: CGPointMake(118.88, 65.82))
        haloPath.addCurveToPoint(CGPointMake(133.51, 60.58), controlPoint1: CGPointMake(125.1, 65.82), controlPoint2: CGPointMake(129.88, 63.83))
        haloPath.addCurveToPoint(CGPointMake(148.01, 65.02), controlPoint1: CGPointMake(137.64, 63.38), controlPoint2: CGPointMake(142.63, 65.02))
        haloPath.addCurveToPoint(CGPointMake(173.85, 39.18), controlPoint1: CGPointMake(162.27, 65.02), controlPoint2: CGPointMake(173.85, 53.45))
        haloPath.addCurveToPoint(CGPointMake(173.33, 34.03), controlPoint1: CGPointMake(173.85, 37.42), controlPoint2: CGPointMake(173.67, 35.69))
        haloPath.addCurveToPoint(CGPointMake(179.78, 24.76), controlPoint1: CGPointMake(177.09, 32.63), controlPoint2: CGPointMake(179.78, 29.02))
        haloPath.closePath()
        haloPath.miterLimit = 4;

        CGContextSaveGState(context)
        CGContextSetShadowWithColor(context, GroupMeBooks.logoShadow.shadowOffset, GroupMeBooks.logoShadow.shadowBlurRadius, (GroupMeBooks.logoShadow.shadowColor as! UIColor).CGColor)
        GroupMeBooks.purple.setFill()
        haloPath.fill()
        CGContextRestoreGState(context)



        //// WordMark
        //// Bezier 2 Drawing
        let bezier2Path = UIBezierPath()
        bezier2Path.moveToPoint(CGPointMake(166.29, 36.28))
        bezier2Path.addCurveToPoint(CGPointMake(149.25, 20.86), controlPoint1: CGPointMake(166.29, 28.54), controlPoint2: CGPointMake(160.09, 20.86))
        bezier2Path.addCurveToPoint(CGPointMake(132.02, 33.89), controlPoint1: CGPointMake(140, 20.86), controlPoint2: CGPointMake(133.86, 25.92))
        bezier2Path.addCurveToPoint(CGPointMake(117.68, 20.86), controlPoint1: CGPointMake(130.41, 25.07), controlPoint2: CGPointMake(124.41, 20.86))
        bezier2Path.addCurveToPoint(CGPointMake(107.74, 26.79), controlPoint1: CGPointMake(113.1, 20.86), controlPoint2: CGPointMake(109.29, 22.79))
        bezier2Path.addLineToPoint(CGPointMake(107.61, 26.79))
        bezier2Path.addLineToPoint(CGPointMake(107.61, 25.31))
        bezier2Path.addCurveToPoint(CGPointMake(103.35, 20.86), controlPoint1: CGPointMake(107.61, 22.41), controlPoint2: CGPointMake(106.13, 20.86))
        bezier2Path.addCurveToPoint(CGPointMake(99.48, 23.09), controlPoint1: CGPointMake(101.32, 20.86), controlPoint2: CGPointMake(100.05, 21.64))
        bezier2Path.addCurveToPoint(CGPointMake(95.28, 20.86), controlPoint1: CGPointMake(98.79, 21.96), controlPoint2: CGPointMake(97.51, 20.86))
        bezier2Path.addCurveToPoint(CGPointMake(90.76, 25.05), controlPoint1: CGPointMake(92.7, 20.86), controlPoint2: CGPointMake(91.41, 22.66))
        bezier2Path.addLineToPoint(CGPointMake(85.02, 46.42))
        bezier2Path.addLineToPoint(CGPointMake(84.89, 46.42))
        bezier2Path.addLineToPoint(CGPointMake(78.82, 24.41))
        bezier2Path.addCurveToPoint(CGPointMake(73.98, 20.86), controlPoint1: CGPointMake(78.24, 22.28), controlPoint2: CGPointMake(76.5, 20.86))
        bezier2Path.addCurveToPoint(CGPointMake(69.92, 23.28), controlPoint1: CGPointMake(72.22, 20.86), controlPoint2: CGPointMake(70.69, 21.82))
        bezier2Path.addCurveToPoint(CGPointMake(65.97, 20.86), controlPoint1: CGPointMake(69.13, 21.84), controlPoint2: CGPointMake(67.51, 20.86))
        bezier2Path.addCurveToPoint(CGPointMake(62.36, 22.66), controlPoint1: CGPointMake(64.55, 20.86), controlPoint2: CGPointMake(63.33, 21.63))
        bezier2Path.addLineToPoint(CGPointMake(51.91, 34.28))
        bezier2Path.addLineToPoint(CGPointMake(51.91, 12.85))
        bezier2Path.addCurveToPoint(CGPointMake(47.19, 8.14), controlPoint1: CGPointMake(51.91, 9.76), controlPoint2: CGPointMake(50.03, 8.14))
        bezier2Path.addCurveToPoint(CGPointMake(42.48, 12.85), controlPoint1: CGPointMake(44.35, 8.14), controlPoint2: CGPointMake(42.48, 9.76))
        bezier2Path.addLineToPoint(CGPointMake(42.48, 42.29))
        bezier2Path.addCurveToPoint(CGPointMake(31.19, 34.99), controlPoint1: CGPointMake(40.95, 37.81), controlPoint2: CGPointMake(35.71, 36.03))
        bezier2Path.addLineToPoint(CGPointMake(27.26, 34.09))
        bezier2Path.addCurveToPoint(CGPointMake(22.21, 30.73), controlPoint1: CGPointMake(24.35, 33.44), controlPoint2: CGPointMake(22.21, 32.93))
        bezier2Path.addCurveToPoint(CGPointMake(27.64, 27.82), controlPoint1: CGPointMake(22.21, 28.73), controlPoint2: CGPointMake(24.35, 27.82))
        bezier2Path.addCurveToPoint(CGPointMake(37.38, 32.15), controlPoint1: CGPointMake(33.58, 27.82), controlPoint2: CGPointMake(33.7, 32.15))
        bezier2Path.addCurveToPoint(CGPointMake(41.32, 28.02), controlPoint1: CGPointMake(39.84, 32.15), controlPoint2: CGPointMake(41.32, 30.22))
        bezier2Path.addCurveToPoint(CGPointMake(26.93, 20.86), controlPoint1: CGPointMake(41.32, 23.7), controlPoint2: CGPointMake(34.09, 20.86))
        bezier2Path.addCurveToPoint(CGPointMake(12.8, 31.38), controlPoint1: CGPointMake(20.41, 20.86), controlPoint2: CGPointMake(12.8, 23.7))
        bezier2Path.addCurveToPoint(CGPointMake(22.54, 41.32), controlPoint1: CGPointMake(12.8, 37.7), controlPoint2: CGPointMake(17.05, 39.96))
        bezier2Path.addLineToPoint(CGPointMake(28.09, 42.67))
        bezier2Path.addCurveToPoint(CGPointMake(33.51, 46.29), controlPoint1: CGPointMake(31.45, 43.51), controlPoint2: CGPointMake(33.51, 43.9))
        bezier2Path.addCurveToPoint(CGPointMake(28.02, 49.71), controlPoint1: CGPointMake(33.51, 48.22), controlPoint2: CGPointMake(31.38, 49.71))
        bezier2Path.addCurveToPoint(CGPointMake(16.6, 43.9), controlPoint1: CGPointMake(21.06, 49.71), controlPoint2: CGPointMake(20.67, 43.9))
        bezier2Path.addCurveToPoint(CGPointMake(12.8, 47.84), controlPoint1: CGPointMake(13.96, 43.9), controlPoint2: CGPointMake(12.8, 45.77))
        bezier2Path.addCurveToPoint(CGPointMake(28.41, 56.29), controlPoint1: CGPointMake(12.8, 52.48), controlPoint2: CGPointMake(19.89, 56.29))
        bezier2Path.addCurveToPoint(CGPointMake(42.48, 48.11), controlPoint1: CGPointMake(34.49, 56.29), controlPoint2: CGPointMake(40.79, 53.68))
        bezier2Path.addLineToPoint(CGPointMake(42.48, 51.58))
        bezier2Path.addCurveToPoint(CGPointMake(47.19, 56.29), controlPoint1: CGPointMake(42.48, 54.68), controlPoint2: CGPointMake(44.35, 56.29))
        bezier2Path.addCurveToPoint(CGPointMake(51.91, 51.58), controlPoint1: CGPointMake(50.03, 56.29), controlPoint2: CGPointMake(51.91, 54.68))
        bezier2Path.addLineToPoint(CGPointMake(51.91, 44.41))
        bezier2Path.addLineToPoint(CGPointMake(55.19, 41.51))
        bezier2Path.addLineToPoint(CGPointMake(64.1, 54.1))
        bezier2Path.addCurveToPoint(CGPointMake(68.36, 56.29), controlPoint1: CGPointMake(64.81, 55.13), controlPoint2: CGPointMake(66.04, 56.29))
        bezier2Path.addCurveToPoint(CGPointMake(72.81, 51.71), controlPoint1: CGPointMake(70.88, 56.29), controlPoint2: CGPointMake(72.81, 54.1))
        bezier2Path.addCurveToPoint(CGPointMake(71.85, 48.67), controlPoint1: CGPointMake(72.81, 50.16), controlPoint2: CGPointMake(72.17, 49.12))
        bezier2Path.addLineToPoint(CGPointMake(62.04, 35.51))
        bezier2Path.addLineToPoint(CGPointMake(69.01, 28.21))
        bezier2Path.addCurveToPoint(CGPointMake(69.76, 27.36), controlPoint1: CGPointMake(69.29, 27.9), controlPoint2: CGPointMake(69.55, 27.64))
        bezier2Path.addCurveToPoint(CGPointMake(70.56, 29.76), controlPoint1: CGPointMake(69.95, 28), controlPoint2: CGPointMake(70.22, 28.75))
        bezier2Path.addLineToPoint(CGPointMake(80.37, 57.71))
        bezier2Path.addCurveToPoint(CGPointMake(77.08, 60.68), controlPoint1: CGPointMake(79.66, 60.61), controlPoint2: CGPointMake(78.3, 60.68))
        bezier2Path.addLineToPoint(CGPointMake(76.11, 60.68))
        bezier2Path.addCurveToPoint(CGPointMake(71.79, 64.48), controlPoint1: CGPointMake(73.59, 60.68), controlPoint2: CGPointMake(71.79, 61.97))
        bezier2Path.addCurveToPoint(CGPointMake(77.72, 68.81), controlPoint1: CGPointMake(71.79, 66.75), controlPoint2: CGPointMake(73.53, 68.81))
        bezier2Path.addCurveToPoint(CGPointMake(88.51, 59), controlPoint1: CGPointMake(83.66, 68.81), controlPoint2: CGPointMake(86.25, 65.45))
        bezier2Path.addLineToPoint(CGPointMake(99.09, 28.99))
        bezier2Path.addLineToPoint(CGPointMake(99.09, 64.1))
        bezier2Path.addCurveToPoint(CGPointMake(103.8, 68.81), controlPoint1: CGPointMake(99.09, 67.2), controlPoint2: CGPointMake(100.96, 68.81))
        bezier2Path.addCurveToPoint(CGPointMake(108.51, 64.1), controlPoint1: CGPointMake(106.64, 68.81), controlPoint2: CGPointMake(108.51, 67.2))
        bezier2Path.addLineToPoint(CGPointMake(108.51, 51.51))
        bezier2Path.addLineToPoint(CGPointMake(108.65, 51.51))
        bezier2Path.addCurveToPoint(CGPointMake(117.94, 56.29), controlPoint1: CGPointMake(110.39, 54.55), controlPoint2: CGPointMake(113.61, 56.29))
        bezier2Path.addCurveToPoint(CGPointMake(131.98, 43.77), controlPoint1: CGPointMake(126.01, 56.29), controlPoint2: CGPointMake(130.55, 50.71))
        bezier2Path.addCurveToPoint(CGPointMake(149.57, 56.29), controlPoint1: CGPointMake(133.57, 50.39), controlPoint2: CGPointMake(138.85, 56.29))
        bezier2Path.addCurveToPoint(CGPointMake(164.35, 47.97), controlPoint1: CGPointMake(155.25, 56.29), controlPoint2: CGPointMake(164.35, 53.64))
        bezier2Path.addCurveToPoint(CGPointMake(160.48, 44.29), controlPoint1: CGPointMake(164.35, 46.22), controlPoint2: CGPointMake(162.73, 44.29))
        bezier2Path.addCurveToPoint(CGPointMake(149.57, 48.93), controlPoint1: CGPointMake(156.67, 44.29), controlPoint2: CGPointMake(156.67, 48.93))
        bezier2Path.addCurveToPoint(CGPointMake(140.86, 40.35), controlPoint1: CGPointMake(144.08, 48.93), controlPoint2: CGPointMake(140.86, 45.32))
        bezier2Path.addLineToPoint(CGPointMake(162.16, 40.35))
        bezier2Path.addCurveToPoint(CGPointMake(166.29, 36.28), controlPoint1: CGPointMake(165.32, 40.35), controlPoint2: CGPointMake(166.29, 39.51))
        bezier2Path.closePath()
        bezier2Path.moveToPoint(CGPointMake(115.55, 48.93))
        bezier2Path.addCurveToPoint(CGPointMake(108, 38.48), controlPoint1: CGPointMake(109.81, 48.93), controlPoint2: CGPointMake(108, 43.32))
        bezier2Path.addCurveToPoint(CGPointMake(115.55, 28.22), controlPoint1: CGPointMake(108, 33.12), controlPoint2: CGPointMake(110.07, 28.15))
        bezier2Path.addCurveToPoint(CGPointMake(123.04, 38.48), controlPoint1: CGPointMake(120.59, 28.28), controlPoint2: CGPointMake(123.04, 32.93))
        bezier2Path.addCurveToPoint(CGPointMake(115.55, 48.93), controlPoint1: CGPointMake(123.04, 42.86), controlPoint2: CGPointMake(121.55, 48.87))
        bezier2Path.closePath()
        bezier2Path.moveToPoint(CGPointMake(140.86, 34.93))
        bezier2Path.addCurveToPoint(CGPointMake(149.44, 27.44), controlPoint1: CGPointMake(141.89, 30.34), controlPoint2: CGPointMake(144.73, 27.44))
        bezier2Path.addCurveToPoint(CGPointMake(157.38, 34.93), controlPoint1: CGPointMake(153.64, 27.44), controlPoint2: CGPointMake(156.86, 30.61))
        bezier2Path.addLineToPoint(CGPointMake(140.86, 34.93))
        bezier2Path.closePath()
        bezier2Path.miterLimit = 4;

        UIColor.whiteColor().setFill()
        bezier2Path.fill()


        //// Bezier 3 Drawing
        let bezier3Path = UIBezierPath()
        bezier3Path.moveToPoint(CGPointMake(163.67, 22.63))
        bezier3Path.addLineToPoint(CGPointMake(163.67, 21.54))
        bezier3Path.addLineToPoint(CGPointMake(168.54, 21.54))
        bezier3Path.addLineToPoint(CGPointMake(168.54, 22.63))
        bezier3Path.addLineToPoint(CGPointMake(166.77, 22.63))
        bezier3Path.addLineToPoint(CGPointMake(166.77, 27.47))
        bezier3Path.addLineToPoint(CGPointMake(165.45, 27.47))
        bezier3Path.addLineToPoint(CGPointMake(165.45, 22.63))
        bezier3Path.addLineToPoint(CGPointMake(163.67, 22.63))
        bezier3Path.closePath()
        bezier3Path.miterLimit = 4;

        GroupMeBooks.white50.setFill()
        bezier3Path.fill()


        //// Bezier 4 Drawing
        let bezier4Path = UIBezierPath()
        bezier4Path.moveToPoint(CGPointMake(171.05, 21.54))
        bezier4Path.addLineToPoint(CGPointMake(172.45, 25.61))
        bezier4Path.addLineToPoint(CGPointMake(172.46, 25.61))
        bezier4Path.addLineToPoint(CGPointMake(173.77, 21.54))
        bezier4Path.addLineToPoint(CGPointMake(175.62, 21.54))
        bezier4Path.addLineToPoint(CGPointMake(175.62, 27.47))
        bezier4Path.addLineToPoint(CGPointMake(174.39, 27.47))
        bezier4Path.addLineToPoint(CGPointMake(174.39, 23.26))
        bezier4Path.addLineToPoint(CGPointMake(174.38, 23.26))
        bezier4Path.addLineToPoint(CGPointMake(172.92, 27.47))
        bezier4Path.addLineToPoint(CGPointMake(171.91, 27.47))
        bezier4Path.addLineToPoint(CGPointMake(170.46, 23.3))
        bezier4Path.addLineToPoint(CGPointMake(170.44, 23.3))
        bezier4Path.addLineToPoint(CGPointMake(170.44, 27.47))
        bezier4Path.addLineToPoint(CGPointMake(169.22, 27.47))
        bezier4Path.addLineToPoint(CGPointMake(169.22, 21.54))
        bezier4Path.addLineToPoint(CGPointMake(171.05, 21.54))
        bezier4Path.closePath()
        bezier4Path.miterLimit = 4;

        GroupMeBooks.white50.setFill()
        bezier4Path.fill()
    }

    public class func drawLogoPurpleOnWhite() {
        //// General Declarations
        let context = UIGraphicsGetCurrentContext()

        //// Group
        //// Halo Drawing
        let haloPath = UIBezierPath()
        haloPath.moveToPoint(CGPointMake(179.78, 24.76))
        haloPath.addCurveToPoint(CGPointMake(169.89, 14.88), controlPoint1: CGPointMake(179.78, 19.3), controlPoint2: CGPointMake(175.35, 14.88))
        haloPath.addCurveToPoint(CGPointMake(162.73, 17.96), controlPoint1: CGPointMake(167.07, 14.88), controlPoint2: CGPointMake(164.53, 16.06))
        haloPath.addCurveToPoint(CGPointMake(148, 13.34), controlPoint1: CGPointMake(158.55, 15.05), controlPoint2: CGPointMake(153.48, 13.34))
        haloPath.addCurveToPoint(CGPointMake(133.16, 18.05), controlPoint1: CGPointMake(142.47, 13.34), controlPoint2: CGPointMake(137.35, 15.1))
        haloPath.addCurveToPoint(CGPointMake(125.96, 15.23), controlPoint1: CGPointMake(131.26, 16.3), controlPoint2: CGPointMake(128.74, 15.23))
        haloPath.addCurveToPoint(CGPointMake(120.34, 16.85), controlPoint1: CGPointMake(123.89, 15.23), controlPoint2: CGPointMake(121.97, 15.83))
        haloPath.addCurveToPoint(CGPointMake(100.64, 5.31), controlPoint1: CGPointMake(116.47, 9.96), controlPoint2: CGPointMake(109.1, 5.31))
        haloPath.addCurveToPoint(CGPointMake(82.02, 15.1), controlPoint1: CGPointMake(92.91, 5.31), controlPoint2: CGPointMake(86.1, 9.19))
        haloPath.addCurveToPoint(CGPointMake(68.57, 9.41), controlPoint1: CGPointMake(78.61, 11.59), controlPoint2: CGPointMake(73.85, 9.41))
        haloPath.addCurveToPoint(CGPointMake(59.04, 12.03), controlPoint1: CGPointMake(65.09, 9.41), controlPoint2: CGPointMake(61.83, 10.38))
        haloPath.addCurveToPoint(CGPointMake(46.89, 0), controlPoint1: CGPointMake(58.97, 5.38), controlPoint2: CGPointMake(53.56, 0))
        haloPath.addCurveToPoint(CGPointMake(34.74, 12.15), controlPoint1: CGPointMake(40.18, 0), controlPoint2: CGPointMake(34.74, 5.44))
        haloPath.addCurveToPoint(CGPointMake(34.77, 12.61), controlPoint1: CGPointMake(34.74, 12.3), controlPoint2: CGPointMake(34.76, 12.45))
        haloPath.addCurveToPoint(CGPointMake(30.77, 12.31), controlPoint1: CGPointMake(33.47, 12.42), controlPoint2: CGPointMake(32.13, 12.31))
        haloPath.addCurveToPoint(CGPointMake(19.71, 14.74), controlPoint1: CGPointMake(26.82, 12.31), controlPoint2: CGPointMake(23.08, 13.19))
        haloPath.addCurveToPoint(CGPointMake(13.38, 13.15), controlPoint1: CGPointMake(17.83, 13.72), controlPoint2: CGPointMake(15.68, 13.15))
        haloPath.addCurveToPoint(CGPointMake(0, 26.53), controlPoint1: CGPointMake(6, 13.15), controlPoint2: CGPointMake(0, 19.14))
        haloPath.addCurveToPoint(CGPointMake(4.38, 36.4), controlPoint1: CGPointMake(0, 30.44), controlPoint2: CGPointMake(1.69, 33.95))
        haloPath.addCurveToPoint(CGPointMake(4.26, 38.83), controlPoint1: CGPointMake(4.3, 37.2), controlPoint2: CGPointMake(4.26, 38.01))
        haloPath.addCurveToPoint(CGPointMake(30.77, 65.35), controlPoint1: CGPointMake(4.26, 53.47), controlPoint2: CGPointMake(16.13, 65.35))
        haloPath.addCurveToPoint(CGPointMake(46.06, 60.5), controlPoint1: CGPointMake(36.47, 65.35), controlPoint2: CGPointMake(41.74, 63.55))
        haloPath.addCurveToPoint(CGPointMake(63.32, 69.29), controlPoint1: CGPointMake(49.95, 65.82), controlPoint2: CGPointMake(56.22, 69.29))
        haloPath.addCurveToPoint(CGPointMake(63.83, 69.27), controlPoint1: CGPointMake(63.49, 69.29), controlPoint2: CGPointMake(63.66, 69.27))
        haloPath.addCurveToPoint(CGPointMake(77.86, 79.22), controlPoint1: CGPointMake(65.87, 75.06), controlPoint2: CGPointMake(71.37, 79.22))
        haloPath.addCurveToPoint(CGPointMake(91.97, 69.04), controlPoint1: CGPointMake(84.43, 79.22), controlPoint2: CGPointMake(90, 74.95))
        haloPath.addCurveToPoint(CGPointMake(103.86, 76.23), controlPoint1: CGPointMake(94.22, 73.31), controlPoint2: CGPointMake(98.7, 76.23))
        haloPath.addCurveToPoint(CGPointMake(116.99, 65.6), controlPoint1: CGPointMake(110.31, 76.23), controlPoint2: CGPointMake(115.7, 71.67))
        haloPath.addCurveToPoint(CGPointMake(119.84, 65.82), controlPoint1: CGPointMake(117.93, 65.73), controlPoint2: CGPointMake(118.88, 65.82))
        haloPath.addCurveToPoint(CGPointMake(133.51, 60.58), controlPoint1: CGPointMake(125.1, 65.82), controlPoint2: CGPointMake(129.88, 63.83))
        haloPath.addCurveToPoint(CGPointMake(148.01, 65.02), controlPoint1: CGPointMake(137.64, 63.38), controlPoint2: CGPointMake(142.63, 65.02))
        haloPath.addCurveToPoint(CGPointMake(173.85, 39.18), controlPoint1: CGPointMake(162.27, 65.02), controlPoint2: CGPointMake(173.85, 53.45))
        haloPath.addCurveToPoint(CGPointMake(173.33, 34.03), controlPoint1: CGPointMake(173.85, 37.42), controlPoint2: CGPointMake(173.67, 35.69))
        haloPath.addCurveToPoint(CGPointMake(179.78, 24.76), controlPoint1: CGPointMake(177.09, 32.63), controlPoint2: CGPointMake(179.78, 29.02))
        haloPath.closePath()
        haloPath.miterLimit = 4;

        CGContextSaveGState(context)
        CGContextSetShadowWithColor(context, GroupMeBooks.logoShadow.shadowOffset, GroupMeBooks.logoShadow.shadowBlurRadius, (GroupMeBooks.logoShadow.shadowColor as! UIColor).CGColor)
        UIColor.whiteColor().setFill()
        haloPath.fill()
        CGContextRestoreGState(context)



        //// WordMark
        //// Bezier 2 Drawing
        let bezier2Path = UIBezierPath()
        bezier2Path.moveToPoint(CGPointMake(166.29, 36.28))
        bezier2Path.addCurveToPoint(CGPointMake(149.25, 20.86), controlPoint1: CGPointMake(166.29, 28.54), controlPoint2: CGPointMake(160.09, 20.86))
        bezier2Path.addCurveToPoint(CGPointMake(132.02, 33.89), controlPoint1: CGPointMake(140, 20.86), controlPoint2: CGPointMake(133.86, 25.92))
        bezier2Path.addCurveToPoint(CGPointMake(117.68, 20.86), controlPoint1: CGPointMake(130.41, 25.07), controlPoint2: CGPointMake(124.41, 20.86))
        bezier2Path.addCurveToPoint(CGPointMake(107.74, 26.79), controlPoint1: CGPointMake(113.1, 20.86), controlPoint2: CGPointMake(109.29, 22.79))
        bezier2Path.addLineToPoint(CGPointMake(107.61, 26.79))
        bezier2Path.addLineToPoint(CGPointMake(107.61, 25.31))
        bezier2Path.addCurveToPoint(CGPointMake(103.35, 20.86), controlPoint1: CGPointMake(107.61, 22.41), controlPoint2: CGPointMake(106.13, 20.86))
        bezier2Path.addCurveToPoint(CGPointMake(99.48, 23.09), controlPoint1: CGPointMake(101.32, 20.86), controlPoint2: CGPointMake(100.05, 21.64))
        bezier2Path.addCurveToPoint(CGPointMake(95.28, 20.86), controlPoint1: CGPointMake(98.79, 21.96), controlPoint2: CGPointMake(97.51, 20.86))
        bezier2Path.addCurveToPoint(CGPointMake(90.76, 25.05), controlPoint1: CGPointMake(92.7, 20.86), controlPoint2: CGPointMake(91.41, 22.66))
        bezier2Path.addLineToPoint(CGPointMake(85.02, 46.42))
        bezier2Path.addLineToPoint(CGPointMake(84.89, 46.42))
        bezier2Path.addLineToPoint(CGPointMake(78.82, 24.41))
        bezier2Path.addCurveToPoint(CGPointMake(73.98, 20.86), controlPoint1: CGPointMake(78.24, 22.28), controlPoint2: CGPointMake(76.5, 20.86))
        bezier2Path.addCurveToPoint(CGPointMake(69.92, 23.28), controlPoint1: CGPointMake(72.22, 20.86), controlPoint2: CGPointMake(70.69, 21.82))
        bezier2Path.addCurveToPoint(CGPointMake(65.97, 20.86), controlPoint1: CGPointMake(69.13, 21.84), controlPoint2: CGPointMake(67.51, 20.86))
        bezier2Path.addCurveToPoint(CGPointMake(62.36, 22.66), controlPoint1: CGPointMake(64.55, 20.86), controlPoint2: CGPointMake(63.33, 21.63))
        bezier2Path.addLineToPoint(CGPointMake(51.91, 34.28))
        bezier2Path.addLineToPoint(CGPointMake(51.91, 12.85))
        bezier2Path.addCurveToPoint(CGPointMake(47.19, 8.14), controlPoint1: CGPointMake(51.91, 9.76), controlPoint2: CGPointMake(50.03, 8.14))
        bezier2Path.addCurveToPoint(CGPointMake(42.48, 12.85), controlPoint1: CGPointMake(44.35, 8.14), controlPoint2: CGPointMake(42.48, 9.76))
        bezier2Path.addLineToPoint(CGPointMake(42.48, 42.29))
        bezier2Path.addCurveToPoint(CGPointMake(31.19, 34.99), controlPoint1: CGPointMake(40.95, 37.81), controlPoint2: CGPointMake(35.71, 36.03))
        bezier2Path.addLineToPoint(CGPointMake(27.26, 34.09))
        bezier2Path.addCurveToPoint(CGPointMake(22.21, 30.73), controlPoint1: CGPointMake(24.35, 33.44), controlPoint2: CGPointMake(22.21, 32.93))
        bezier2Path.addCurveToPoint(CGPointMake(27.64, 27.82), controlPoint1: CGPointMake(22.21, 28.73), controlPoint2: CGPointMake(24.35, 27.82))
        bezier2Path.addCurveToPoint(CGPointMake(37.38, 32.15), controlPoint1: CGPointMake(33.58, 27.82), controlPoint2: CGPointMake(33.7, 32.15))
        bezier2Path.addCurveToPoint(CGPointMake(41.32, 28.02), controlPoint1: CGPointMake(39.84, 32.15), controlPoint2: CGPointMake(41.32, 30.22))
        bezier2Path.addCurveToPoint(CGPointMake(26.93, 20.86), controlPoint1: CGPointMake(41.32, 23.7), controlPoint2: CGPointMake(34.09, 20.86))
        bezier2Path.addCurveToPoint(CGPointMake(12.8, 31.38), controlPoint1: CGPointMake(20.41, 20.86), controlPoint2: CGPointMake(12.8, 23.7))
        bezier2Path.addCurveToPoint(CGPointMake(22.54, 41.32), controlPoint1: CGPointMake(12.8, 37.7), controlPoint2: CGPointMake(17.05, 39.96))
        bezier2Path.addLineToPoint(CGPointMake(28.09, 42.67))
        bezier2Path.addCurveToPoint(CGPointMake(33.51, 46.29), controlPoint1: CGPointMake(31.45, 43.51), controlPoint2: CGPointMake(33.51, 43.9))
        bezier2Path.addCurveToPoint(CGPointMake(28.02, 49.71), controlPoint1: CGPointMake(33.51, 48.22), controlPoint2: CGPointMake(31.38, 49.71))
        bezier2Path.addCurveToPoint(CGPointMake(16.6, 43.9), controlPoint1: CGPointMake(21.06, 49.71), controlPoint2: CGPointMake(20.67, 43.9))
        bezier2Path.addCurveToPoint(CGPointMake(12.8, 47.84), controlPoint1: CGPointMake(13.96, 43.9), controlPoint2: CGPointMake(12.8, 45.77))
        bezier2Path.addCurveToPoint(CGPointMake(28.41, 56.29), controlPoint1: CGPointMake(12.8, 52.48), controlPoint2: CGPointMake(19.89, 56.29))
        bezier2Path.addCurveToPoint(CGPointMake(42.48, 48.11), controlPoint1: CGPointMake(34.49, 56.29), controlPoint2: CGPointMake(40.79, 53.68))
        bezier2Path.addLineToPoint(CGPointMake(42.48, 51.58))
        bezier2Path.addCurveToPoint(CGPointMake(47.19, 56.29), controlPoint1: CGPointMake(42.48, 54.68), controlPoint2: CGPointMake(44.35, 56.29))
        bezier2Path.addCurveToPoint(CGPointMake(51.91, 51.58), controlPoint1: CGPointMake(50.03, 56.29), controlPoint2: CGPointMake(51.91, 54.68))
        bezier2Path.addLineToPoint(CGPointMake(51.91, 44.41))
        bezier2Path.addLineToPoint(CGPointMake(55.19, 41.51))
        bezier2Path.addLineToPoint(CGPointMake(64.1, 54.1))
        bezier2Path.addCurveToPoint(CGPointMake(68.36, 56.29), controlPoint1: CGPointMake(64.81, 55.13), controlPoint2: CGPointMake(66.04, 56.29))
        bezier2Path.addCurveToPoint(CGPointMake(72.81, 51.71), controlPoint1: CGPointMake(70.88, 56.29), controlPoint2: CGPointMake(72.81, 54.1))
        bezier2Path.addCurveToPoint(CGPointMake(71.85, 48.67), controlPoint1: CGPointMake(72.81, 50.16), controlPoint2: CGPointMake(72.17, 49.12))
        bezier2Path.addLineToPoint(CGPointMake(62.04, 35.51))
        bezier2Path.addLineToPoint(CGPointMake(69.01, 28.21))
        bezier2Path.addCurveToPoint(CGPointMake(69.76, 27.36), controlPoint1: CGPointMake(69.29, 27.9), controlPoint2: CGPointMake(69.55, 27.64))
        bezier2Path.addCurveToPoint(CGPointMake(70.56, 29.76), controlPoint1: CGPointMake(69.95, 28), controlPoint2: CGPointMake(70.22, 28.75))
        bezier2Path.addLineToPoint(CGPointMake(80.37, 57.71))
        bezier2Path.addCurveToPoint(CGPointMake(77.08, 60.68), controlPoint1: CGPointMake(79.66, 60.61), controlPoint2: CGPointMake(78.3, 60.68))
        bezier2Path.addLineToPoint(CGPointMake(76.11, 60.68))
        bezier2Path.addCurveToPoint(CGPointMake(71.79, 64.48), controlPoint1: CGPointMake(73.59, 60.68), controlPoint2: CGPointMake(71.79, 61.97))
        bezier2Path.addCurveToPoint(CGPointMake(77.72, 68.81), controlPoint1: CGPointMake(71.79, 66.75), controlPoint2: CGPointMake(73.53, 68.81))
        bezier2Path.addCurveToPoint(CGPointMake(88.51, 59), controlPoint1: CGPointMake(83.66, 68.81), controlPoint2: CGPointMake(86.25, 65.45))
        bezier2Path.addLineToPoint(CGPointMake(99.09, 28.99))
        bezier2Path.addLineToPoint(CGPointMake(99.09, 64.1))
        bezier2Path.addCurveToPoint(CGPointMake(103.8, 68.81), controlPoint1: CGPointMake(99.09, 67.2), controlPoint2: CGPointMake(100.96, 68.81))
        bezier2Path.addCurveToPoint(CGPointMake(108.51, 64.1), controlPoint1: CGPointMake(106.64, 68.81), controlPoint2: CGPointMake(108.51, 67.2))
        bezier2Path.addLineToPoint(CGPointMake(108.51, 51.51))
        bezier2Path.addLineToPoint(CGPointMake(108.65, 51.51))
        bezier2Path.addCurveToPoint(CGPointMake(117.94, 56.29), controlPoint1: CGPointMake(110.39, 54.55), controlPoint2: CGPointMake(113.61, 56.29))
        bezier2Path.addCurveToPoint(CGPointMake(131.98, 43.77), controlPoint1: CGPointMake(126.01, 56.29), controlPoint2: CGPointMake(130.55, 50.71))
        bezier2Path.addCurveToPoint(CGPointMake(149.57, 56.29), controlPoint1: CGPointMake(133.57, 50.39), controlPoint2: CGPointMake(138.85, 56.29))
        bezier2Path.addCurveToPoint(CGPointMake(164.35, 47.97), controlPoint1: CGPointMake(155.25, 56.29), controlPoint2: CGPointMake(164.35, 53.64))
        bezier2Path.addCurveToPoint(CGPointMake(160.48, 44.29), controlPoint1: CGPointMake(164.35, 46.22), controlPoint2: CGPointMake(162.73, 44.29))
        bezier2Path.addCurveToPoint(CGPointMake(149.57, 48.93), controlPoint1: CGPointMake(156.67, 44.29), controlPoint2: CGPointMake(156.67, 48.93))
        bezier2Path.addCurveToPoint(CGPointMake(140.86, 40.35), controlPoint1: CGPointMake(144.08, 48.93), controlPoint2: CGPointMake(140.86, 45.32))
        bezier2Path.addLineToPoint(CGPointMake(162.16, 40.35))
        bezier2Path.addCurveToPoint(CGPointMake(166.29, 36.28), controlPoint1: CGPointMake(165.32, 40.35), controlPoint2: CGPointMake(166.29, 39.51))
        bezier2Path.closePath()
        bezier2Path.moveToPoint(CGPointMake(115.55, 48.93))
        bezier2Path.addCurveToPoint(CGPointMake(108, 38.48), controlPoint1: CGPointMake(109.81, 48.93), controlPoint2: CGPointMake(108, 43.32))
        bezier2Path.addCurveToPoint(CGPointMake(115.55, 28.22), controlPoint1: CGPointMake(108, 33.12), controlPoint2: CGPointMake(110.07, 28.15))
        bezier2Path.addCurveToPoint(CGPointMake(123.04, 38.48), controlPoint1: CGPointMake(120.59, 28.28), controlPoint2: CGPointMake(123.04, 32.93))
        bezier2Path.addCurveToPoint(CGPointMake(115.55, 48.93), controlPoint1: CGPointMake(123.04, 42.86), controlPoint2: CGPointMake(121.55, 48.87))
        bezier2Path.closePath()
        bezier2Path.moveToPoint(CGPointMake(140.86, 34.93))
        bezier2Path.addCurveToPoint(CGPointMake(149.44, 27.44), controlPoint1: CGPointMake(141.89, 30.34), controlPoint2: CGPointMake(144.73, 27.44))
        bezier2Path.addCurveToPoint(CGPointMake(157.38, 34.93), controlPoint1: CGPointMake(153.64, 27.44), controlPoint2: CGPointMake(156.86, 30.61))
        bezier2Path.addLineToPoint(CGPointMake(140.86, 34.93))
        bezier2Path.closePath()
        bezier2Path.miterLimit = 4;

        GroupMeBooks.purple.setFill()
        bezier2Path.fill()


        //// Bezier 3 Drawing
        let bezier3Path = UIBezierPath()
        bezier3Path.moveToPoint(CGPointMake(163.67, 22.63))
        bezier3Path.addLineToPoint(CGPointMake(163.67, 21.54))
        bezier3Path.addLineToPoint(CGPointMake(168.54, 21.54))
        bezier3Path.addLineToPoint(CGPointMake(168.54, 22.63))
        bezier3Path.addLineToPoint(CGPointMake(166.77, 22.63))
        bezier3Path.addLineToPoint(CGPointMake(166.77, 27.47))
        bezier3Path.addLineToPoint(CGPointMake(165.45, 27.47))
        bezier3Path.addLineToPoint(CGPointMake(165.45, 22.63))
        bezier3Path.addLineToPoint(CGPointMake(163.67, 22.63))
        bezier3Path.closePath()
        bezier3Path.miterLimit = 4;

        GroupMeBooks.purple.setFill()
        bezier3Path.fill()


        //// Bezier 4 Drawing
        let bezier4Path = UIBezierPath()
        bezier4Path.moveToPoint(CGPointMake(171.05, 21.54))
        bezier4Path.addLineToPoint(CGPointMake(172.45, 25.61))
        bezier4Path.addLineToPoint(CGPointMake(172.46, 25.61))
        bezier4Path.addLineToPoint(CGPointMake(173.77, 21.54))
        bezier4Path.addLineToPoint(CGPointMake(175.62, 21.54))
        bezier4Path.addLineToPoint(CGPointMake(175.62, 27.47))
        bezier4Path.addLineToPoint(CGPointMake(174.39, 27.47))
        bezier4Path.addLineToPoint(CGPointMake(174.39, 23.26))
        bezier4Path.addLineToPoint(CGPointMake(174.38, 23.26))
        bezier4Path.addLineToPoint(CGPointMake(172.92, 27.47))
        bezier4Path.addLineToPoint(CGPointMake(171.91, 27.47))
        bezier4Path.addLineToPoint(CGPointMake(170.46, 23.3))
        bezier4Path.addLineToPoint(CGPointMake(170.44, 23.3))
        bezier4Path.addLineToPoint(CGPointMake(170.44, 27.47))
        bezier4Path.addLineToPoint(CGPointMake(169.22, 27.47))
        bezier4Path.addLineToPoint(CGPointMake(169.22, 21.54))
        bezier4Path.addLineToPoint(CGPointMake(171.05, 21.54))
        bezier4Path.closePath()
        bezier4Path.miterLimit = 4;

        GroupMeBooks.purple.setFill()
        bezier4Path.fill()
    }

    public class func drawFace() {

        //// path2999 Drawing
        let path2999Path = UIBezierPath()
        path2999Path.moveToPoint(CGPointMake(25.54, 48.66))
        path2999Path.addCurveToPoint(CGPointMake(19.25, 47.41), controlPoint1: CGPointMake(23.44, 48.55), controlPoint2: CGPointMake(21.19, 48.35))
        path2999Path.addCurveToPoint(CGPointMake(9.51, 33.8), controlPoint1: CGPointMake(14.36, 45.07), controlPoint2: CGPointMake(11.15, 38.92))
        path2999Path.addCurveToPoint(CGPointMake(8.24, 28.19), controlPoint1: CGPointMake(8.93, 31.98), controlPoint2: CGPointMake(8.53, 30.08))
        path2999Path.addCurveToPoint(CGPointMake(7.75, 22.34), controlPoint1: CGPointMake(7.96, 26.26), controlPoint2: CGPointMake(7.81, 24.29))
        path2999Path.addCurveToPoint(CGPointMake(10.86, 7), controlPoint1: CGPointMake(7.6, 16.98), controlPoint2: CGPointMake(7.54, 11.35))
        path2999Path.addCurveToPoint(CGPointMake(16.38, 2.62), controlPoint1: CGPointMake(12.31, 5.1), controlPoint2: CGPointMake(14.21, 3.49))
        path2999Path.addCurveToPoint(CGPointMake(19.95, 1.82), controlPoint1: CGPointMake(17.53, 2.15), controlPoint2: CGPointMake(18.73, 1.99))
        path2999Path.addCurveToPoint(CGPointMake(27.24, 1.38), controlPoint1: CGPointMake(22.36, 1.47), controlPoint2: CGPointMake(24.81, 1.29))
        path2999Path.addCurveToPoint(CGPointMake(34.24, 2.66), controlPoint1: CGPointMake(29.56, 1.48), controlPoint2: CGPointMake(32.08, 1.68))
        path2999Path.addCurveToPoint(CGPointMake(42.28, 11.69), controlPoint1: CGPointMake(37.81, 4.29), controlPoint2: CGPointMake(41.04, 7.77))
        path2999Path.addCurveToPoint(CGPointMake(43.1, 19.52), controlPoint1: CGPointMake(43.07, 14.15), controlPoint2: CGPointMake(43.05, 16.96))
        path2999Path.addCurveToPoint(CGPointMake(41.27, 33.8), controlPoint1: CGPointMake(43.2, 24.33), controlPoint2: CGPointMake(42.74, 29.22))
        path2999Path.addCurveToPoint(CGPointMake(31.21, 47.69), controlPoint1: CGPointMake(39.55, 39.18), controlPoint2: CGPointMake(36.57, 45.53))
        path2999Path.addCurveToPoint(CGPointMake(25.54, 48.66), controlPoint1: CGPointMake(29.38, 48.42), controlPoint2: CGPointMake(27.48, 48.62))
        path2999Path.closePath()
        path2999Path.moveToPoint(CGPointMake(26.78, 50))
        path2999Path.addCurveToPoint(CGPointMake(32.51, 48.55), controlPoint1: CGPointMake(28.78, 49.77), controlPoint2: CGPointMake(30.67, 49.45))
        path2999Path.addCurveToPoint(CGPointMake(38.61, 42.47), controlPoint1: CGPointMake(35.08, 47.3), controlPoint2: CGPointMake(37.1, 44.93))
        path2999Path.addCurveToPoint(CGPointMake(43.53, 28.57), controlPoint1: CGPointMake(41.2, 38.24), controlPoint2: CGPointMake(42.6, 33.46))
        path2999Path.addCurveToPoint(CGPointMake(44.46, 27.12), controlPoint1: CGPointMake(44.03, 28.19), controlPoint2: CGPointMake(44.43, 27.82))
        path2999Path.addCurveToPoint(CGPointMake(45, 16.28), controlPoint1: CGPointMake(44.66, 23.51), controlPoint2: CGPointMake(44.85, 19.89))
        path2999Path.addCurveToPoint(CGPointMake(43.85, 14.57), controlPoint1: CGPointMake(45.03, 15.4), controlPoint2: CGPointMake(44.54, 14.91))
        path2999Path.addCurveToPoint(CGPointMake(43.26, 10.92), controlPoint1: CGPointMake(43.74, 13.35), controlPoint2: CGPointMake(43.66, 12.08))
        path2999Path.addCurveToPoint(CGPointMake(33.9, 1.03), controlPoint1: CGPointMake(41.73, 6.48), controlPoint2: CGPointMake(38.23, 2.5))
        path2999Path.addCurveToPoint(CGPointMake(25.42, 0), controlPoint1: CGPointMake(31.14, 0.1), controlPoint2: CGPointMake(28.28, 0.05))
        path2999Path.addCurveToPoint(CGPointMake(15.86, 1.33), controlPoint1: CGPointMake(22.25, 0.12), controlPoint2: CGPointMake(18.85, 0.06))
        path2999Path.addCurveToPoint(CGPointMake(7.49, 10.91), controlPoint1: CGPointMake(11.85, 3.02), controlPoint2: CGPointMake(8.82, 6.6))
        path2999Path.addCurveToPoint(CGPointMake(6.96, 14.62), controlPoint1: CGPointMake(7.13, 12.1), controlPoint2: CGPointMake(7.06, 13.38))
        path2999Path.addCurveToPoint(CGPointMake(6, 16.28), controlPoint1: CGPointMake(6.36, 14.97), controlPoint2: CGPointMake(5.97, 15.51))
        path2999Path.addCurveToPoint(CGPointMake(6.54, 27.12), controlPoint1: CGPointMake(6.16, 19.89), controlPoint2: CGPointMake(6.34, 23.51))
        path2999Path.addCurveToPoint(CGPointMake(7.26, 28.44), controlPoint1: CGPointMake(6.57, 27.71), controlPoint2: CGPointMake(6.85, 28.09))
        path2999Path.addCurveToPoint(CGPointMake(12.45, 42.61), controlPoint1: CGPointMake(8.18, 33.49), controlPoint2: CGPointMake(9.64, 38.32))
        path2999Path.addCurveToPoint(CGPointMake(18.89, 48.71), controlPoint1: CGPointMake(14.1, 45.12), controlPoint2: CGPointMake(16.22, 47.42))
        path2999Path.addCurveToPoint(CGPointMake(26.78, 50), controlPoint1: CGPointMake(21.36, 49.89), controlPoint2: CGPointMake(24.11, 50.01))
        path2999Path.closePath()
        path2999Path.miterLimit = 4;

        GroupMeBooks.purple.setFill()
        path2999Path.fill()
    }

    public class func drawLogoPurpleOnWhiteSmall() {
        //// General Declarations
        let context = UIGraphicsGetCurrentContext()

        //// Group
        //// Halo Drawing
        let haloPath = UIBezierPath()
        haloPath.moveToPoint(CGPointMake(96.78, 18.88))
        haloPath.addCurveToPoint(CGPointMake(91.67, 13.74), controlPoint1: CGPointMake(96.78, 16.04), controlPoint2: CGPointMake(94.49, 13.74))
        haloPath.addCurveToPoint(CGPointMake(87.98, 15.34), controlPoint1: CGPointMake(90.22, 13.74), controlPoint2: CGPointMake(88.91, 14.36))
        haloPath.addCurveToPoint(CGPointMake(80.38, 12.94), controlPoint1: CGPointMake(85.82, 13.83), controlPoint2: CGPointMake(83.2, 12.94))
        haloPath.addCurveToPoint(CGPointMake(72.72, 15.39), controlPoint1: CGPointMake(77.52, 12.94), controlPoint2: CGPointMake(74.88, 13.85))
        haloPath.addCurveToPoint(CGPointMake(69, 13.92), controlPoint1: CGPointMake(71.74, 14.48), controlPoint2: CGPointMake(70.44, 13.92))
        haloPath.addCurveToPoint(CGPointMake(66.1, 14.77), controlPoint1: CGPointMake(67.94, 13.92), controlPoint2: CGPointMake(66.94, 14.24))
        haloPath.addCurveToPoint(CGPointMake(55.94, 8.76), controlPoint1: CGPointMake(64.11, 11.18), controlPoint2: CGPointMake(60.3, 8.76))
        haloPath.addCurveToPoint(CGPointMake(46.33, 13.85), controlPoint1: CGPointMake(51.95, 8.76), controlPoint2: CGPointMake(48.43, 10.78))
        haloPath.addCurveToPoint(CGPointMake(39.39, 10.9), controlPoint1: CGPointMake(44.57, 12.03), controlPoint2: CGPointMake(42.11, 10.9))
        haloPath.addCurveToPoint(CGPointMake(34.47, 12.26), controlPoint1: CGPointMake(37.59, 10.9), controlPoint2: CGPointMake(35.91, 11.4))
        haloPath.addCurveToPoint(CGPointMake(28.2, 6), controlPoint1: CGPointMake(34.43, 8.8), controlPoint2: CGPointMake(31.64, 6))
        haloPath.addCurveToPoint(CGPointMake(21.93, 12.32), controlPoint1: CGPointMake(24.74, 6), controlPoint2: CGPointMake(21.93, 8.83))
        haloPath.addCurveToPoint(CGPointMake(21.94, 12.56), controlPoint1: CGPointMake(21.93, 12.4), controlPoint2: CGPointMake(21.94, 12.48))
        haloPath.addCurveToPoint(CGPointMake(19.88, 12.4), controlPoint1: CGPointMake(21.27, 12.46), controlPoint2: CGPointMake(20.58, 12.4))
        haloPath.addCurveToPoint(CGPointMake(14.17, 13.67), controlPoint1: CGPointMake(17.84, 12.4), controlPoint2: CGPointMake(15.91, 12.86))
        haloPath.addCurveToPoint(CGPointMake(10.91, 12.84), controlPoint1: CGPointMake(13.2, 13.14), controlPoint2: CGPointMake(12.09, 12.84))
        haloPath.addCurveToPoint(CGPointMake(4, 19.8), controlPoint1: CGPointMake(7.09, 12.84), controlPoint2: CGPointMake(4, 15.96))
        haloPath.addCurveToPoint(CGPointMake(6.26, 24.94), controlPoint1: CGPointMake(4, 21.84), controlPoint2: CGPointMake(4.87, 23.67))
        haloPath.addCurveToPoint(CGPointMake(6.2, 26.2), controlPoint1: CGPointMake(6.22, 25.35), controlPoint2: CGPointMake(6.2, 25.78))
        haloPath.addCurveToPoint(CGPointMake(19.88, 40), controlPoint1: CGPointMake(6.2, 33.82), controlPoint2: CGPointMake(12.32, 40))
        haloPath.addCurveToPoint(CGPointMake(27.77, 37.48), controlPoint1: CGPointMake(22.82, 40), controlPoint2: CGPointMake(25.54, 39.06))
        haloPath.addCurveToPoint(CGPointMake(36.68, 42.05), controlPoint1: CGPointMake(29.78, 40.24), controlPoint2: CGPointMake(33.01, 42.05))
        haloPath.addCurveToPoint(CGPointMake(36.94, 42.04), controlPoint1: CGPointMake(36.77, 42.05), controlPoint2: CGPointMake(36.85, 42.04))
        haloPath.addCurveToPoint(CGPointMake(44.18, 47.22), controlPoint1: CGPointMake(37.99, 45.05), controlPoint2: CGPointMake(40.83, 47.22))
        haloPath.addCurveToPoint(CGPointMake(51.46, 41.92), controlPoint1: CGPointMake(47.57, 47.22), controlPoint2: CGPointMake(50.44, 45))
        haloPath.addCurveToPoint(CGPointMake(57.6, 45.66), controlPoint1: CGPointMake(52.63, 44.14), controlPoint2: CGPointMake(54.93, 45.66))
        haloPath.addCurveToPoint(CGPointMake(64.38, 40.13), controlPoint1: CGPointMake(60.93, 45.66), controlPoint2: CGPointMake(63.71, 43.29))
        haloPath.addCurveToPoint(CGPointMake(65.85, 40.24), controlPoint1: CGPointMake(64.86, 40.2), controlPoint2: CGPointMake(65.35, 40.24))
        haloPath.addCurveToPoint(CGPointMake(72.9, 37.52), controlPoint1: CGPointMake(68.56, 40.24), controlPoint2: CGPointMake(71.03, 39.21))
        haloPath.addCurveToPoint(CGPointMake(80.38, 39.83), controlPoint1: CGPointMake(75.03, 38.98), controlPoint2: CGPointMake(77.61, 39.83))
        haloPath.addCurveToPoint(CGPointMake(93.72, 26.39), controlPoint1: CGPointMake(87.74, 39.83), controlPoint2: CGPointMake(93.72, 33.81))
        haloPath.addCurveToPoint(CGPointMake(93.45, 23.7), controlPoint1: CGPointMake(93.72, 25.47), controlPoint2: CGPointMake(93.62, 24.57))
        haloPath.addCurveToPoint(CGPointMake(96.78, 18.88), controlPoint1: CGPointMake(95.39, 22.98), controlPoint2: CGPointMake(96.78, 21.1))
        haloPath.closePath()
        haloPath.miterLimit = 4;

        CGContextSaveGState(context)
        CGContextSetShadowWithColor(context, GroupMeBooks.logoShadow.shadowOffset, GroupMeBooks.logoShadow.shadowBlurRadius, (GroupMeBooks.logoShadow.shadowColor as! UIColor).CGColor)
        UIColor.whiteColor().setFill()
        haloPath.fill()
        CGContextRestoreGState(context)



        //// WordMark
        //// Bezier 2 Drawing
        let bezier2Path = UIBezierPath()
        bezier2Path.moveToPoint(CGPointMake(89.82, 24.83))
        bezier2Path.addCurveToPoint(CGPointMake(81.04, 16.78), controlPoint1: CGPointMake(89.82, 20.79), controlPoint2: CGPointMake(86.62, 16.78))
        bezier2Path.addCurveToPoint(CGPointMake(72.17, 23.58), controlPoint1: CGPointMake(76.28, 16.78), controlPoint2: CGPointMake(73.12, 19.42))
        bezier2Path.addCurveToPoint(CGPointMake(64.79, 16.78), controlPoint1: CGPointMake(71.34, 18.98), controlPoint2: CGPointMake(68.25, 16.78))
        bezier2Path.addCurveToPoint(CGPointMake(59.67, 19.88), controlPoint1: CGPointMake(62.43, 16.78), controlPoint2: CGPointMake(60.47, 17.79))
        bezier2Path.addLineToPoint(CGPointMake(59.61, 19.88))
        bezier2Path.addLineToPoint(CGPointMake(59.61, 19.1))
        bezier2Path.addCurveToPoint(CGPointMake(57.41, 16.78), controlPoint1: CGPointMake(59.61, 17.59), controlPoint2: CGPointMake(58.84, 16.78))
        bezier2Path.addCurveToPoint(CGPointMake(55.42, 17.95), controlPoint1: CGPointMake(56.37, 16.78), controlPoint2: CGPointMake(55.72, 17.19))
        bezier2Path.addCurveToPoint(CGPointMake(53.26, 16.78), controlPoint1: CGPointMake(55.07, 17.35), controlPoint2: CGPointMake(54.41, 16.78))
        bezier2Path.addCurveToPoint(CGPointMake(50.93, 18.97), controlPoint1: CGPointMake(51.93, 16.78), controlPoint2: CGPointMake(51.27, 17.72))
        bezier2Path.addLineToPoint(CGPointMake(47.98, 30.12))
        bezier2Path.addLineToPoint(CGPointMake(47.91, 30.12))
        bezier2Path.addLineToPoint(CGPointMake(44.79, 18.63))
        bezier2Path.addCurveToPoint(CGPointMake(42.29, 16.78), controlPoint1: CGPointMake(44.49, 17.52), controlPoint2: CGPointMake(43.59, 16.78))
        bezier2Path.addCurveToPoint(CGPointMake(40.21, 18.04), controlPoint1: CGPointMake(41.39, 16.78), controlPoint2: CGPointMake(40.6, 17.28))
        bezier2Path.addCurveToPoint(CGPointMake(38.17, 16.78), controlPoint1: CGPointMake(39.8, 17.29), controlPoint2: CGPointMake(38.96, 16.78))
        bezier2Path.addCurveToPoint(CGPointMake(36.31, 17.72), controlPoint1: CGPointMake(37.44, 16.78), controlPoint2: CGPointMake(36.81, 17.18))
        bezier2Path.addLineToPoint(CGPointMake(30.93, 23.79))
        bezier2Path.addLineToPoint(CGPointMake(30.93, 12.6))
        bezier2Path.addCurveToPoint(CGPointMake(28.5, 10.14), controlPoint1: CGPointMake(30.93, 10.99), controlPoint2: CGPointMake(29.96, 10.14))
        bezier2Path.addCurveToPoint(CGPointMake(26.08, 12.6), controlPoint1: CGPointMake(27.04, 10.14), controlPoint2: CGPointMake(26.08, 10.99))
        bezier2Path.addLineToPoint(CGPointMake(26.08, 27.97))
        bezier2Path.addCurveToPoint(CGPointMake(20.26, 24.15), controlPoint1: CGPointMake(25.29, 25.63), controlPoint2: CGPointMake(22.59, 24.7))
        bezier2Path.addLineToPoint(CGPointMake(18.24, 23.69))
        bezier2Path.addCurveToPoint(CGPointMake(15.64, 21.93), controlPoint1: CGPointMake(16.74, 23.35), controlPoint2: CGPointMake(15.64, 23.08))
        bezier2Path.addCurveToPoint(CGPointMake(18.44, 20.42), controlPoint1: CGPointMake(15.64, 20.89), controlPoint2: CGPointMake(16.74, 20.42))
        bezier2Path.addCurveToPoint(CGPointMake(23.45, 22.67), controlPoint1: CGPointMake(21.49, 20.42), controlPoint2: CGPointMake(21.56, 22.67))
        bezier2Path.addCurveToPoint(CGPointMake(25.48, 20.52), controlPoint1: CGPointMake(24.72, 22.67), controlPoint2: CGPointMake(25.48, 21.67))
        bezier2Path.addCurveToPoint(CGPointMake(18.07, 16.78), controlPoint1: CGPointMake(25.48, 18.26), controlPoint2: CGPointMake(21.76, 16.78))
        bezier2Path.addCurveToPoint(CGPointMake(10.8, 22.27), controlPoint1: CGPointMake(14.71, 16.78), controlPoint2: CGPointMake(10.8, 18.26))
        bezier2Path.addCurveToPoint(CGPointMake(15.81, 27.46), controlPoint1: CGPointMake(10.8, 25.57), controlPoint2: CGPointMake(12.99, 26.75))
        bezier2Path.addLineToPoint(CGPointMake(18.67, 28.17))
        bezier2Path.addCurveToPoint(CGPointMake(21.46, 30.05), controlPoint1: CGPointMake(20.4, 28.6), controlPoint2: CGPointMake(21.46, 28.81))
        bezier2Path.addCurveToPoint(CGPointMake(18.63, 31.84), controlPoint1: CGPointMake(21.46, 31.06), controlPoint2: CGPointMake(20.36, 31.84))
        bezier2Path.addCurveToPoint(CGPointMake(12.75, 28.81), controlPoint1: CGPointMake(15.05, 31.84), controlPoint2: CGPointMake(14.85, 28.81))
        bezier2Path.addCurveToPoint(CGPointMake(10.8, 30.86), controlPoint1: CGPointMake(11.39, 28.81), controlPoint2: CGPointMake(10.8, 29.78))
        bezier2Path.addCurveToPoint(CGPointMake(18.84, 35.27), controlPoint1: CGPointMake(10.8, 33.29), controlPoint2: CGPointMake(14.45, 35.27))
        bezier2Path.addCurveToPoint(CGPointMake(26.08, 31), controlPoint1: CGPointMake(21.96, 35.27), controlPoint2: CGPointMake(25.21, 33.91))
        bezier2Path.addLineToPoint(CGPointMake(26.08, 32.81))
        bezier2Path.addCurveToPoint(CGPointMake(28.5, 35.27), controlPoint1: CGPointMake(26.08, 34.43), controlPoint2: CGPointMake(27.04, 35.27))
        bezier2Path.addCurveToPoint(CGPointMake(30.93, 32.81), controlPoint1: CGPointMake(29.96, 35.27), controlPoint2: CGPointMake(30.93, 34.43))
        bezier2Path.addLineToPoint(CGPointMake(30.93, 29.07))
        bezier2Path.addLineToPoint(CGPointMake(32.62, 27.56))
        bezier2Path.addLineToPoint(CGPointMake(37.21, 34.13))
        bezier2Path.addCurveToPoint(CGPointMake(39.4, 35.27), controlPoint1: CGPointMake(37.57, 34.67), controlPoint2: CGPointMake(38.21, 35.27))
        bezier2Path.addCurveToPoint(CGPointMake(41.69, 32.88), controlPoint1: CGPointMake(40.7, 35.27), controlPoint2: CGPointMake(41.69, 34.13))
        bezier2Path.addCurveToPoint(CGPointMake(41.2, 31.3), controlPoint1: CGPointMake(41.69, 32.07), controlPoint2: CGPointMake(41.36, 31.53))
        bezier2Path.addLineToPoint(CGPointMake(36.15, 24.43))
        bezier2Path.addLineToPoint(CGPointMake(39.73, 20.62))
        bezier2Path.addCurveToPoint(CGPointMake(40.12, 20.17), controlPoint1: CGPointMake(39.88, 20.46), controlPoint2: CGPointMake(40.01, 20.32))
        bezier2Path.addCurveToPoint(CGPointMake(40.53, 21.43), controlPoint1: CGPointMake(40.22, 20.51), controlPoint2: CGPointMake(40.36, 20.9))
        bezier2Path.addLineToPoint(CGPointMake(45.58, 36.01))
        bezier2Path.addCurveToPoint(CGPointMake(43.89, 37.56), controlPoint1: CGPointMake(45.22, 37.53), controlPoint2: CGPointMake(44.52, 37.56))
        bezier2Path.addLineToPoint(CGPointMake(43.39, 37.56))
        bezier2Path.addCurveToPoint(CGPointMake(41.16, 39.55), controlPoint1: CGPointMake(42.09, 37.56), controlPoint2: CGPointMake(41.16, 38.24))
        bezier2Path.addCurveToPoint(CGPointMake(44.22, 41.81), controlPoint1: CGPointMake(41.16, 40.73), controlPoint2: CGPointMake(42.06, 41.81))
        bezier2Path.addCurveToPoint(CGPointMake(49.77, 36.69), controlPoint1: CGPointMake(47.28, 41.81), controlPoint2: CGPointMake(48.61, 40.05))
        bezier2Path.addLineToPoint(CGPointMake(55.22, 21.02))
        bezier2Path.addLineToPoint(CGPointMake(55.22, 39.35))
        bezier2Path.addCurveToPoint(CGPointMake(57.65, 41.81), controlPoint1: CGPointMake(55.22, 40.97), controlPoint2: CGPointMake(56.18, 41.81))
        bezier2Path.addCurveToPoint(CGPointMake(60.07, 39.35), controlPoint1: CGPointMake(59.11, 41.81), controlPoint2: CGPointMake(60.07, 40.97))
        bezier2Path.addLineToPoint(CGPointMake(60.07, 32.78))
        bezier2Path.addLineToPoint(CGPointMake(60.14, 32.78))
        bezier2Path.addCurveToPoint(CGPointMake(64.92, 35.27), controlPoint1: CGPointMake(61.04, 34.36), controlPoint2: CGPointMake(62.7, 35.27))
        bezier2Path.addCurveToPoint(CGPointMake(72.15, 28.74), controlPoint1: CGPointMake(69.08, 35.27), controlPoint2: CGPointMake(71.42, 32.36))
        bezier2Path.addCurveToPoint(CGPointMake(81.21, 35.27), controlPoint1: CGPointMake(72.97, 32.19), controlPoint2: CGPointMake(75.69, 35.27))
        bezier2Path.addCurveToPoint(CGPointMake(88.82, 30.93), controlPoint1: CGPointMake(84.13, 35.27), controlPoint2: CGPointMake(88.82, 33.89))
        bezier2Path.addCurveToPoint(CGPointMake(86.82, 29.01), controlPoint1: CGPointMake(88.82, 30.02), controlPoint2: CGPointMake(87.98, 29.01))
        bezier2Path.addCurveToPoint(CGPointMake(81.21, 31.43), controlPoint1: CGPointMake(84.86, 29.01), controlPoint2: CGPointMake(84.86, 31.43))
        bezier2Path.addCurveToPoint(CGPointMake(76.72, 26.95), controlPoint1: CGPointMake(78.38, 31.43), controlPoint2: CGPointMake(76.72, 29.55))
        bezier2Path.addLineToPoint(CGPointMake(87.69, 26.95))
        bezier2Path.addCurveToPoint(CGPointMake(89.82, 24.83), controlPoint1: CGPointMake(89.32, 26.95), controlPoint2: CGPointMake(89.82, 26.51))
        bezier2Path.closePath()
        bezier2Path.moveToPoint(CGPointMake(63.69, 31.43))
        bezier2Path.addCurveToPoint(CGPointMake(59.81, 25.98), controlPoint1: CGPointMake(60.74, 31.43), controlPoint2: CGPointMake(59.81, 28.5))
        bezier2Path.addCurveToPoint(CGPointMake(63.69, 20.62), controlPoint1: CGPointMake(59.81, 23.18), controlPoint2: CGPointMake(60.87, 20.59))
        bezier2Path.addCurveToPoint(CGPointMake(67.55, 25.98), controlPoint1: CGPointMake(66.29, 20.65), controlPoint2: CGPointMake(67.55, 23.08))
        bezier2Path.addCurveToPoint(CGPointMake(63.69, 31.43), controlPoint1: CGPointMake(67.55, 28.27), controlPoint2: CGPointMake(66.79, 31.4))
        bezier2Path.closePath()
        bezier2Path.moveToPoint(CGPointMake(76.72, 24.12))
        bezier2Path.addCurveToPoint(CGPointMake(81.14, 20.22), controlPoint1: CGPointMake(77.25, 21.73), controlPoint2: CGPointMake(78.71, 20.22))
        bezier2Path.addCurveToPoint(CGPointMake(85.23, 24.12), controlPoint1: CGPointMake(83.3, 20.22), controlPoint2: CGPointMake(84.96, 21.87))
        bezier2Path.addLineToPoint(CGPointMake(76.72, 24.12))
        bezier2Path.closePath()
        bezier2Path.miterLimit = 4;

        GroupMeBooks.purple.setFill()
        bezier2Path.fill()


        //// Bezier 3 Drawing
        let bezier3Path = UIBezierPath()
        bezier3Path.moveToPoint(CGPointMake(88.47, 17.7))
        bezier3Path.addLineToPoint(CGPointMake(88.47, 17.13))
        bezier3Path.addLineToPoint(CGPointMake(90.98, 17.13))
        bezier3Path.addLineToPoint(CGPointMake(90.98, 17.7))
        bezier3Path.addLineToPoint(CGPointMake(90.06, 17.7))
        bezier3Path.addLineToPoint(CGPointMake(90.06, 20.23))
        bezier3Path.addLineToPoint(CGPointMake(89.38, 20.23))
        bezier3Path.addLineToPoint(CGPointMake(89.38, 17.7))
        bezier3Path.addLineToPoint(CGPointMake(88.47, 17.7))
        bezier3Path.closePath()
        bezier3Path.miterLimit = 4;

        GroupMeBooks.purple.setFill()
        bezier3Path.fill()


        //// Bezier 4 Drawing
        let bezier4Path = UIBezierPath()
        bezier4Path.moveToPoint(CGPointMake(92.27, 17.13))
        bezier4Path.addLineToPoint(CGPointMake(92.99, 19.26))
        bezier4Path.addLineToPoint(CGPointMake(92.99, 19.26))
        bezier4Path.addLineToPoint(CGPointMake(93.67, 17.13))
        bezier4Path.addLineToPoint(CGPointMake(94.62, 17.13))
        bezier4Path.addLineToPoint(CGPointMake(94.62, 20.23))
        bezier4Path.addLineToPoint(CGPointMake(93.99, 20.23))
        bezier4Path.addLineToPoint(CGPointMake(93.99, 18.03))
        bezier4Path.addLineToPoint(CGPointMake(93.98, 18.03))
        bezier4Path.addLineToPoint(CGPointMake(93.23, 20.23))
        bezier4Path.addLineToPoint(CGPointMake(92.71, 20.23))
        bezier4Path.addLineToPoint(CGPointMake(91.96, 18.06))
        bezier4Path.addLineToPoint(CGPointMake(91.95, 18.06))
        bezier4Path.addLineToPoint(CGPointMake(91.95, 20.23))
        bezier4Path.addLineToPoint(CGPointMake(91.32, 20.23))
        bezier4Path.addLineToPoint(CGPointMake(91.32, 17.13))
        bezier4Path.addLineToPoint(CGPointMake(92.27, 17.13))
        bezier4Path.closePath()
        bezier4Path.miterLimit = 4;

        GroupMeBooks.purple.setFill()
        bezier4Path.fill()
    }

    public class func drawSingleBubble() {
        //// General Declarations
        let context = UIGraphicsGetCurrentContext()


        //// Shadow Declarations
        let cardShadow = NSShadow(color: GroupMeBooks.shadowColor.colorWithAlphaComponent(0.28 * CGColorGetAlpha(GroupMeBooks.shadowColor.CGColor)), offset: CGSizeMake(0.1, 2.1), blurRadius: 2)

        //// Bezier 11 Drawing
        let bezier11Path = UIBezierPath()
        bezier11Path.moveToPoint(CGPointMake(29.33, 4.29))
        bezier11Path.addCurveToPoint(CGPointMake(24.98, 0), controlPoint1: CGPointMake(29.33, 1.92), controlPoint2: CGPointMake(27.38, 0))
        bezier11Path.addLineToPoint(CGPointMake(5.86, 0))
        bezier11Path.addCurveToPoint(CGPointMake(1.5, 4.29), controlPoint1: CGPointMake(3.45, 0), controlPoint2: CGPointMake(1.5, 1.92))
        bezier11Path.addLineToPoint(CGPointMake(1.5, 12.87))
        bezier11Path.addCurveToPoint(CGPointMake(5.86, 17.16), controlPoint1: CGPointMake(1.5, 15.24), controlPoint2: CGPointMake(3.45, 17.16))
        bezier11Path.addLineToPoint(CGPointMake(10.55, 17.16))
        bezier11Path.addLineToPoint(CGPointMake(11.25, 22.5))
        bezier11Path.addLineToPoint(CGPointMake(16.02, 17.16))
        bezier11Path.addLineToPoint(CGPointMake(24.98, 17.16))
        bezier11Path.addCurveToPoint(CGPointMake(29.33, 12.87), controlPoint1: CGPointMake(27.38, 17.16), controlPoint2: CGPointMake(29.33, 15.24))
        bezier11Path.addLineToPoint(CGPointMake(29.33, 4.29))
        bezier11Path.closePath()
        bezier11Path.miterLimit = 4;

        bezier11Path.lineJoinStyle = .Round;

        CGContextSaveGState(context)
        CGContextSetShadowWithColor(context, cardShadow.shadowOffset, cardShadow.shadowBlurRadius, (cardShadow.shadowColor as! UIColor).CGColor)
        CGContextBeginTransparencyLayer(context, nil)
        bezier11Path.addClip()
        CGContextDrawRadialGradient(context, GroupMeBooks.slateGradient,
            CGPointMake(15.42, 0), 2.01,
            CGPointMake(15.42, 11.25), 13.68,
            [CGGradientDrawingOptions.DrawsBeforeStartLocation, CGGradientDrawingOptions.DrawsAfterEndLocation])
        CGContextEndTransparencyLayer(context)
        CGContextRestoreGState(context)

        GroupMeBooks.white10.setStroke()
        bezier11Path.lineWidth = 1
        bezier11Path.stroke()
    }

    public class func drawDualBubble() {
        //// General Declarations
        let context = UIGraphicsGetCurrentContext()


        //// Shadow Declarations
        let cardShadow = NSShadow(color: GroupMeBooks.shadowColor.colorWithAlphaComponent(0.28 * CGColorGetAlpha(GroupMeBooks.shadowColor.CGColor)), offset: CGSizeMake(0.1, 2.1), blurRadius: 2)

        //// Group 2
        //// Bezier 8 Drawing
        let bezier8Path = UIBezierPath()
        bezier8Path.moveToPoint(CGPointMake(21, 9.15))
        bezier8Path.addCurveToPoint(CGPointMake(18.03, 6), controlPoint1: CGPointMake(21, 7.41), controlPoint2: CGPointMake(19.67, 6))
        bezier8Path.addLineToPoint(CGPointMake(4.97, 6))
        bezier8Path.addCurveToPoint(CGPointMake(2, 9.15), controlPoint1: CGPointMake(3.33, 6), controlPoint2: CGPointMake(2, 7.41))
        bezier8Path.addLineToPoint(CGPointMake(2, 15.44))
        bezier8Path.addCurveToPoint(CGPointMake(4.97, 18.58), controlPoint1: CGPointMake(2, 17.18), controlPoint2: CGPointMake(3.33, 18.58))
        bezier8Path.addLineToPoint(CGPointMake(8.17, 18.58))
        bezier8Path.addLineToPoint(CGPointMake(8.65, 22.5))
        bezier8Path.addLineToPoint(CGPointMake(11.91, 18.58))
        bezier8Path.addLineToPoint(CGPointMake(18.03, 18.58))
        bezier8Path.addCurveToPoint(CGPointMake(21, 15.44), controlPoint1: CGPointMake(19.67, 18.58), controlPoint2: CGPointMake(21, 17.18))
        bezier8Path.addLineToPoint(CGPointMake(21, 9.15))
        bezier8Path.closePath()
        bezier8Path.miterLimit = 4;

        bezier8Path.lineJoinStyle = .Round;

        CGContextSaveGState(context)
        CGContextSetShadowWithColor(context, cardShadow.shadowOffset, cardShadow.shadowBlurRadius, (cardShadow.shadowColor as! UIColor).CGColor)
        CGContextBeginTransparencyLayer(context, nil)
        bezier8Path.addClip()
        CGContextDrawRadialGradient(context, GroupMeBooks.slateGradient,
            CGPointMake(11.5, 6.34), 1.41,
            CGPointMake(11.5, 14.25), 9.62,
            [CGGradientDrawingOptions.DrawsBeforeStartLocation, CGGradientDrawingOptions.DrawsAfterEndLocation])
        CGContextEndTransparencyLayer(context)
        CGContextRestoreGState(context)

        GroupMeBooks.white10.setStroke()
        bezier8Path.lineWidth = 1
        bezier8Path.stroke()


        //// Bezier 9 Drawing
        let bezier9Path = UIBezierPath()
        bezier9Path.moveToPoint(CGPointMake(26.83, 3.15))
        bezier9Path.addCurveToPoint(CGPointMake(23.73, 0), controlPoint1: CGPointMake(26.83, 1.41), controlPoint2: CGPointMake(25.44, 0))
        bezier9Path.addLineToPoint(CGPointMake(10.11, 0))
        bezier9Path.addCurveToPoint(CGPointMake(7, 3.15), controlPoint1: CGPointMake(8.39, 0), controlPoint2: CGPointMake(7, 1.41))
        bezier9Path.addLineToPoint(CGPointMake(7, 9.44))
        bezier9Path.addCurveToPoint(CGPointMake(10.11, 12.58), controlPoint1: CGPointMake(7, 11.18), controlPoint2: CGPointMake(8.39, 12.58))
        bezier9Path.addLineToPoint(CGPointMake(13.45, 12.58))
        bezier9Path.addLineToPoint(CGPointMake(13.95, 16.5))
        bezier9Path.addLineToPoint(CGPointMake(17.35, 12.58))
        bezier9Path.addLineToPoint(CGPointMake(23.73, 12.58))
        bezier9Path.addCurveToPoint(CGPointMake(26.83, 9.44), controlPoint1: CGPointMake(25.44, 12.58), controlPoint2: CGPointMake(26.83, 11.18))
        bezier9Path.addLineToPoint(CGPointMake(26.83, 3.15))
        bezier9Path.closePath()
        bezier9Path.miterLimit = 4;

        bezier9Path.lineJoinStyle = .Round;

        CGContextSaveGState(context)
        CGContextSetShadowWithColor(context, cardShadow.shadowOffset, cardShadow.shadowBlurRadius, (cardShadow.shadowColor as! UIColor).CGColor)
        CGContextBeginTransparencyLayer(context, nil)
        bezier9Path.addClip()
        CGContextDrawRadialGradient(context, GroupMeBooks.slateGradient,
            CGPointMake(16.92, 0.14), 1.45,
            CGPointMake(16.92, 8.25), 9.86,
            [CGGradientDrawingOptions.DrawsBeforeStartLocation, CGGradientDrawingOptions.DrawsAfterEndLocation])
        CGContextEndTransparencyLayer(context)
        CGContextRestoreGState(context)

        GroupMeBooks.white10.setStroke()
        bezier9Path.lineWidth = 1
        bezier9Path.stroke()
    }

    //// Generated Images

    public class var imageOfLogoPurpleOnWhite: UIImage {
        if Cache.imageOfLogoPurpleOnWhite != nil {
            return Cache.imageOfLogoPurpleOnWhite!
        }

        UIGraphicsBeginImageContextWithOptions(CGSizeMake(180, 85), false, 0)
            GroupMeBooks.drawLogoPurpleOnWhite()

        Cache.imageOfLogoPurpleOnWhite = UIGraphicsGetImageFromCurrentImageContext()
        UIGraphicsEndImageContext()

        return Cache.imageOfLogoPurpleOnWhite!
    }

    public class var imageOfFace: UIImage {
        if Cache.imageOfFace != nil {
            return Cache.imageOfFace!
        }

        UIGraphicsBeginImageContextWithOptions(CGSizeMake(50, 50), false, 0)
            GroupMeBooks.drawFace()

        Cache.imageOfFace = UIGraphicsGetImageFromCurrentImageContext()
        UIGraphicsEndImageContext()

        return Cache.imageOfFace!
    }

    public class var imageOfLogoPurpleOnWhiteSmall: UIImage {
        if Cache.imageOfLogoPurpleOnWhiteSmall != nil {
            return Cache.imageOfLogoPurpleOnWhiteSmall!
        }

        UIGraphicsBeginImageContextWithOptions(CGSizeMake(100, 53), false, 0)
            GroupMeBooks.drawLogoPurpleOnWhiteSmall()

        Cache.imageOfLogoPurpleOnWhiteSmall = UIGraphicsGetImageFromCurrentImageContext()
        UIGraphicsEndImageContext()

        return Cache.imageOfLogoPurpleOnWhiteSmall!
    }

    public class var imageOfSingleBubble: UIImage {
        if Cache.imageOfSingleBubble != nil {
            return Cache.imageOfSingleBubble!
        }

        UIGraphicsBeginImageContextWithOptions(CGSizeMake(31, 25), false, 0)
            GroupMeBooks.drawSingleBubble()

        Cache.imageOfSingleBubble = UIGraphicsGetImageFromCurrentImageContext()
        UIGraphicsEndImageContext()

        return Cache.imageOfSingleBubble!
    }

    public class var imageOfDualBubble: UIImage {
        if Cache.imageOfDualBubble != nil {
            return Cache.imageOfDualBubble!
        }

        UIGraphicsBeginImageContextWithOptions(CGSizeMake(29, 25), false, 0)
            GroupMeBooks.drawDualBubble()

        Cache.imageOfDualBubble = UIGraphicsGetImageFromCurrentImageContext()
        UIGraphicsEndImageContext()

        return Cache.imageOfDualBubble!
    }

    //// Customization Infrastructure

    @IBOutlet var logoPurpleOnWhiteTargets: [AnyObject]! {
        get { return Cache.logoPurpleOnWhiteTargets }
        set {
            Cache.logoPurpleOnWhiteTargets = newValue
            for target: AnyObject in newValue {
                target.performSelector("setImage:", withObject: GroupMeBooks.imageOfLogoPurpleOnWhite)
            }
        }
    }

    @IBOutlet var faceTargets: [AnyObject]! {
        get { return Cache.faceTargets }
        set {
            Cache.faceTargets = newValue
            for target: AnyObject in newValue {
                target.performSelector("setImage:", withObject: GroupMeBooks.imageOfFace)
            }
        }
    }

    @IBOutlet var logoPurpleOnWhiteSmallTargets: [AnyObject]! {
        get { return Cache.logoPurpleOnWhiteSmallTargets }
        set {
            Cache.logoPurpleOnWhiteSmallTargets = newValue
            for target: AnyObject in newValue {
                target.performSelector("setImage:", withObject: GroupMeBooks.imageOfLogoPurpleOnWhiteSmall)
            }
        }
    }

    @IBOutlet var singleBubbleTargets: [AnyObject]! {
        get { return Cache.singleBubbleTargets }
        set {
            Cache.singleBubbleTargets = newValue
            for target: AnyObject in newValue {
                target.performSelector("setImage:", withObject: GroupMeBooks.imageOfSingleBubble)
            }
        }
    }

    @IBOutlet var dualBubbleTargets: [AnyObject]! {
        get { return Cache.dualBubbleTargets }
        set {
            Cache.dualBubbleTargets = newValue
            for target: AnyObject in newValue {
                target.performSelector("setImage:", withObject: GroupMeBooks.imageOfDualBubble)
            }
        }
    }

}



extension NSShadow {
    convenience init(color: AnyObject!, offset: CGSize, blurRadius: CGFloat) {
        self.init()
        self.shadowColor = color
        self.shadowOffset = offset
        self.shadowBlurRadius = blurRadius
    }
}
